### PR TITLE
Some changes to enable multiroom support in Home Assistant

### PR DESCRIPTION
**Pull request by lyghtnox**
Hi,
I'm currently working on a multiroom support for snap cast in Home Assistant. These changes are needed to enable it. 
Here is what I did:

- Creating method in client class to retrieve all groups on the server
- Adding an update workflow of the server's properties on the `group.add_client` and `group.remove_client` methods (Fixing #29) 
- Adding a client callback in the `server._on_group_stream_changed`

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Looks good -- please update the tests though

**Comment by lyghtnox** [comment]
Tests updated!

**Comment by happyleavesaoc** [comment]
Thanks!

**Comment by lyghtnox** [comment]
Quick question, are you going to update the pypi package someday?

**Comment by happyleavesaoc** [comment]
Just published `2.0.10`.

**Comment by lyghtnox** [comment]
Oh ok thanks!

**Pull request merged**
