### PR TITLE
Set group volume now changes client volume relative to the volume change

### PR DESCRIPTION
**Pull request by D3v01dZA**
I replicated the [Snapweb](https://github.com/badaix/snapcast/blob/master/server/etc/snapweb/snapcontrol.js#L483) logic for changing group volume. Since groups don't store volume themselves you will lose accuracy with each volume change (e.g. setting to 100 group volume still sets all clients to 100 which is still undesirable).

I wanted to write tests but Python is not a primary language for me but I think that I need to add an accessor to retrieve a specific client from the Group so I can check its volume after setting the group's if you would like tests to be added.

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Thanks!

**Comment by D3v01dZA** [comment]
Just noticed that you didn't add a tag for 2.1.2, I got added for an upstream diff and noted all other versions have one! Thanks!

**Comment by happyleavesaoc** [comment]
Added

**Comment by D3v01dZA** [comment]
Thanks!

**Comment by hawkeye217** [comment]
Might need to refactor this commit - if ``current_volume`` is 100, it's possible to run into an issue where you'll divide by zero and throw an exception.

**Comment by D3v01dZA** [comment]
You're right, but this can only happen when the current volume is 100 and the new volume is 100, right?

I did overlook this one, on the UI and in Home Assistant its just a slider which doesn't emit an event when the state remains the same. I can make an early escape to prevent this exception from happening but it will only likely happen this afternoon.

**Comment by hawkeye217** [comment]
That's correct. I ran into the problem because I have a ``media_player.volume_set`` service call in a couple of my HA automations that explicitly sets the value to 1.0 (100). It was likely that the volume was already at 100 via the UI, thus throwing the error.

Thanks for looking!

**Comment by D3v01dZA** [comment]
#38 should fix this issue. I'll wait for @happyleavesaoc to have a look at it and take it into Home Assistant once ready.

**Comment by D3v01dZA** [comment]
https://github.com/home-assistant/core/pull/49553 - for you to follow :)

**Pull request merged**
