### PR TITLE
New server callbacks: connect, disconnect, new client

### PR DESCRIPTION
**Pull request by airdrummingfool**
This is my first attempt at #7, providing callbacks for snapserver connection and disconnection.

Some things to note:
* I'm not a huge fan of declaring the `SERVER_ON(DIS)CONNECT` constants in both `server.py` and `protocol.py`- please let me know if this can be improved somehow.
* This includes my proposed solution to #5 (new client callback) as well. Please let me know if you'd rather I remove that change from this PR.

Thanks!

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Import those constants from `protocol`, in `server`. That way we reduce duplication and keep our imports one-way.

There's a test and lint failure -- once those are green this can be merged!

**Comment by airdrummingfool** [comment]
Ah, importing the constants from `protocol.py` is a great solution - I didn't realize that was possible. Done.

The tests had all passed for me, but I was running them on python 3.6. I just set up `pyenv` and am now able to run the tests against 3.5... apparently I was using a 3.6+ mock method (oops). Fixed.

I fixed one linter error, but there is another one (and it's the only reason for the most recent Travis failure): `Too many public methods (23/20)` in `snapcast.control.server`. I'm not sure what to do about that.

**Comment by airdrummingfool** [comment]
I just found an interesting drawback to this approach. Originally, I was simply waiting for `server.start()` to return before grabbing all clients so I could attach a callback to each. Once I implemented the `on_connect` callback, I moved my subscription code there.

However, the `on_connect` callback is fired _as soon as the connection is made_, i.e. before the server can run `synchronize()` to get state from snapserver. This means that when the callback is fired, there are no clients yet available. Furthermore, the `new_client` callback (also in this PR) is only fired for clients that are newly connected after the first `synchronize()` completes, which means (with my subscription code in callbacks) I don't have a way to know when to pull the initial list of clients.

I can think of a few solutions:
1. Move the trigger for the `on_connect` callback to the end of `server.start()`, once the initial client state has been established. This "fixes" the `on_connect` callback to work how I'd expect, but it means internally it is implemented completely different than the `on_disconnect` callback, which is triggered from `protocol.py` (I don't know if this is a problem).
1. Change my project's code back to waiting for `start()` to return. This is easy, but it leaves the `on_connect` callback essentially useless and behaving in a way that I wasn't expecting (this could just be me making bad assumptions).
1. Change `synchronize()` to call `_on_client_connect()` when initially iterating through clients, instead of adding new client data directly to `self._clients`. This would trigger the `new_client` callback for every discovered client, including ones already connected to snapserver when we first run `synchronize()`. I don't mind this approach, but I'm not sure if it is intuitive to have the `new_client` callback called for clients that were already connected to snapserver when we connect. It also leaves the `on_connect` callback in a pretty useless state (IMO). It's worth noting that I already tried to do this earlier, but abandoned it when I found out that `_on_client_connect()` expects a different data object structure than is immediately available in `synchronize()`s client `for` loop (this can be fixed by boxing the `client` data into a dict with keys `id` and `client`).

What do you think? I prefer option 1, unless it is important to keep the parallel between `on_connect` and `on_disconnect`.

**Comment by airdrummingfool** [comment]
I went ahead and added a commit that implemented 1. above. If you like it, great! If not, I'm happy to strip it from the branch and take a different approach. As before, the only Travis failure is a linter error about too many public methods.

**Comment by happyleavesaoc** [comment]
Option 1 is good! Keeps it simple, and usable. You'll want to disable that linter error.  You can do it like this:

`# pylint: disable=too-many-public-methods`

Put that line directly above the function definition.

**Comment by airdrummingfool** [comment]
Great!

I couldn't figure out which function definition you were referring to, and the pylint comment didn't seem to do anything when I tried it above a couple public function definitions. Instead, I placed directly before the class definition, which resolved the issue. Please let me know if it needs to be moved.

**Comment by happyleavesaoc** [comment]
Yep, sorry, that's a `class` scoped error, so that is the right place!

**Comment by airdrummingfool** [comment]
Thank you! do you have a release scheduled, or a thought on when you might push out a new version to pypi?

**Comment by happyleavesaoc** [comment]
Published `2.0.3` to pypi.

**Pull request merged**
