### PR TITLE
Metadata

### PR DESCRIPTION
**Pull request by frafall**
Hi, I have added support for metadata, ref snapcast pull [request](https://github.com/badaix/snapcast/pull/319).
- new property: stream.meta
- new function stream.set_meta()
- Modified server/stream to support metadata update notifications

Regards,
frafall

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Please update the tests, if you don't mind.

**Comment by frafall** [comment]
Sure, Ill look at it :)

**Comment by frafall** [comment]
Tests now run without faults but no new tests has been added, I'm not certain what level you expect?

I'm kinda new to github pulls, do I need to send a new pull request including the latest commit?

**Comment by happyleavesaoc** [comment]
@frafall there should be a test for every public function, so in this case, `stream_setmeta` in the server, and the various `meta` functions in the stream. You should be able to basically copy-and-paste some of the existing tests and just change a few names.

You can push those commits to your current branch, and this pull request will update automatically.

**Comment by happyleavesaoc** [comment]
@frafall I see your change got merged into `snapcast` for `0.13.0`. Would like to merge this PR too! Let me know if you need any help with the tests.

**Pull request merged**
