### PR TITLE
 Implement add and remove streams and path property

### LINKED ISSUE #31: Snapcast 0.16.x features
Hi, I just wanted to document that there's some new features in snapcast 0.16.0 that would be great to integrate into this project.  See https://github.com/badaix/snapcast/blob/master/changelog.md#version-0160

Notable changes:
* Streams can be added and removed
* Group names can be changed

Maybe the control interface could expose additional functionality if the sever version is higher than 0.16.0?  I may be able to write up a PR in the next few days.

### PR DESCRIPTION
**Pull request by luar123**
Implement functions for adding and removing streams and the stream path property. Basically a copy of #59 but with synchronization on stream remove and added tests.
Fix #31

### CODE REVIEW

**Comment by luar123** [comment]
Depends on #66. I will wait until this one is merged.

**Comment by happyleavesaoc** [comment]
Merged #66, will release after this one is merged too.

**Comment by luar123** [comment]
Thanks!
Rebased on master branch, ready for merging.

**Comment by happyleavesaoc** [comment]
Published `2.3.6` with this change. Thank you!

**Pull request merged**
